version: "1.0.0"
author: "NexusArchive Team"
skillFormat: "aiss-1.0"

tags: [refactoring, simplification, code-quality]
platforms: [claude, copilot, gemini]

triggers:
  keywords:
    - "极简重构"
    - "代码简化"
    - "删减"
    - "复杂度"
    - "过度工程"
    - "cognitive load"
    - "simplify"
  filePatterns:
    - "**/src/**/*.ts"
    - "**/src/**/*.tsx"
    - "**/src/**/*.java"
    - "**/src/**/*.py"
  excludePatterns:
    - "**/node_modules/**"
    - "**/dist/**"
