version: "1.0.0"
author: "NexusArchive Team"
skillFormat: "aiss-1.0"

tags: [architecture, dependency, enforcement]
platforms: [claude, copilot, gemini]

depends:
  - tool: "dependency-cruiser"
    version: ">=14.0.0"
  - tool: "archunit"
    version: ">=1.0.0"

triggers:
  keywords:
    - "架构防御"
    - "依赖约束"
    - "dependency-cruiser"
    - "ArchUnit"
    - "架构守卫"
    - "模块违规"
    - "cross-module"
  filePatterns:
    - "**/src/**/*.ts"
    - "**/src/**/*.tsx"
    - "**/src/**/*.java"
    - "**/manifest.config.ts"
  excludePatterns:
    - "**/node_modules/**"
    - "**/dist/**"
