/**
 * J4: REFLEX
 * J3: CLOSED RULES
 *
 * GitHub Actions workflow that enforces architecture governance.
 * Violations block CI/CD pipeline - PRs cannot merge until fixed.
 *
 * Features:
 * - Runs dependency-cruiser on frontend
 * - Runs ArchUnit tests on backend
 * - Reports violations as PR comments
 * - Fails fast on architecture violations
 */

name: Architecture Governance

on:
  push:
    branches: [main, develop]
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main, develop]

# Cancel in-progress runs for the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  architecture-check-frontend:
    name: Frontend Architecture Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Full history for better analysis

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run dependency-cruiser
        id: depcruise
        run: |
          npx depcruise \
            --config dependency-cruiser.config.cjs \
            --output-type json \
            src \
            > dependency-cruiser-report.json || true

          npx depcruise \
            --config dependency-cruiser.config.cjs \
            --output-type text \
            src \
            > dependency-cruiser-report.txt || true

          # Check for violations
          if [ -s dependency-cruiser-report.json ]; then
            VIOLATIONS=$(cat dependency-cruiser-report.json | jq '.summary.violations')
            if [ "$VIOLATIONS" -gt 0 ]; then
              echo "::error::Found $VIOLATIONS architecture violation(s)"
              exit 1
            fi
          fi

      - name: Generate dependency graph (on failure)
        if: failure()
        run: |
          npx depcruise \
            --config dependency-cruiser.config.cjs \
            --output-type dot \
            src \
            --prefix "file://$GITHUB_WORKSPACE/" \
            | dot -T svg \
            > dependency-graph.svg

      - name: Upload violation reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: frontend-architecture-report
          path: |
            dependency-cruiser-report.json
            dependency-cruiser-report.txt
            dependency-graph.svg
          retention-days: 30

      - name: Comment PR with violations
        if: github.event_name == 'pull_request' && failure()
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const report = fs.readFileSync('dependency-cruiser-report.txt', 'utf8');
            const graphSvg = fs.readFileSync('dependency-graph.svg', 'utf8');

            const body = `## 🔴 Architecture Violations Detected

            Your pull request has **${{ steps.depcruise.outputs.violations }}** architecture violation(s).

            ### Summary
            \`\`\`
            ${report}
            \`\`\`

            ### Next Steps
            1. Review the violations above
            2. Fix the architectural issues
            3. Run \`npx depcruise src\` locally to verify
            4. Push your changes

            ### Dependency Graph
            <details>
            <summary>View dependency graph</summary>

            ![Dependency Graph](data:image/svg+xml;base64,${Buffer.from(graphSvg).toString('base64')})

            </details>

            ---
            🔒 This check enforces our **J4: Reflex** principle - violations block merging.
            `;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            });

  architecture-check-backend:
    name: Backend Architecture Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      - name: Run ArchUnit tests
        id: archunit
        run: |
          ./gradlew test --tests "*ArchitectureRulesTest*" \
            --continue \
            || true

      - name: Parse ArchUnit results
        if: always()
        id: parse-results
        run: |
          # Check if ArchUnit tests passed
          if [ -f build/test-results/test/*.xml ]; then
            FAILURES=$(grep -c 'failure message' build/test-results/test/*Architecture*.xml || echo "0")

            if [ "$FAILURES" -gt 0 ]; then
              echo "violations=$FAILURES" >> $GITHUB_OUTPUT
              echo "::error::Found $FAILURES architecture violation(s)"
              exit 1
            fi
          fi

      - name: Generate HTML report
        if: always()
        run: |
          ./gradlew archunitReport || true

      - name: Upload ArchUnit reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: backend-architecture-report
          path: |
            build/reports/tests/test/classes/**/*Architecture*.html
            build/archunit-report/
          retention-days: 30

      - name: Comment PR with violations
        if: github.event_name == 'pull_request' && failure()
        uses: actions/github-script@v7
        with:
          script: |
            const violations = '${{ steps.parse-results.outputs.violations }}';

            const body = `## 🔴 Backend Architecture Violations Detected

            Your pull request has **${violations}** architecture violation(s).

            ### Common Issues
            - UI layer accessing database models
            - Circular dependencies between packages
            - Services exposing database entities instead of DTOs

            ### Next Steps
            1. Run \`./gradlew test --tests "*ArchitectureRulesTest*"\` locally
            2. Review the specific violations in the logs
            3. Refactor to comply with architecture rules
            4. Push your changes

            ### Documentation
            - [Architecture Guidelines](https://docs.internal.com/architecture)
            - [J1-J4 Framework](https://docs.internal.com/j-framework)

            ---
            🔒 This check enforces our **J4: Reflex** principle - violations block merging.
            `;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            });

  architecture-summary:
    name: Architecture Check Summary
    runs-on: ubuntu-latest
    needs: [architecture-check-frontend, architecture-check-backend]
    if: always()

    steps:
      - name: Check results
        run: |
          if [ "${{ needs.architecture-check-frontend.result }}" != "success" ]; then
            echo "::error::Frontend architecture checks failed"
            exit 1
          fi

          if [ "${{ needs.architecture-check-backend.result }}" != "success" ]; then
            echo "::error::Backend architecture checks failed"
            exit 1
          fi

          echo "✅ All architecture checks passed!"

      - name: Post success comment
        if: github.event_name == 'pull_request' && success()
        uses: actions/github-script@v7
        with:
          script: |
            const body = `## ✅ Architecture Checks Passed

            All architecture governance checks passed successfully.

            ### Verified
            - ✅ No circular dependencies
            - ✅ No UI → Database layer violations
            - ✅ No cross-feature internal imports
            - ✅ Layer hierarchy enforced

            ### J Framework Compliance
            - **J1 Self-Description**: All modules have manifests
            - **J2 Self-Check**: dependency-cruiser + ArchUnit passing
            - **J3 Closed Rules**: Rules applied to build itself
            - **J4 Reflex**: Violations blocked (none found)

            ---
            🎉 Your code is ready to merge!
            `;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            });
